version: '3.8'
networks:
  proansible.ai:
    name: proansible.ai

services:
  control:
    hostname: control
    container_name: control
    image: rheosai/proansible:ubuntu
    ports:
     - ${CONTROL_SSH_PORT}:22
    privileged: true
    volumes:
     - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
     - proansible.ai
