version: '3.8'
networks:
  proansible.ai:
    name: proansible.ai

services:
  control:
    hostname: control
    container_name: control
    image: rheosai/proansible:control
    ports:
     - ${CONTROL_SSH_PORT}:22
     - ${CONTROL_HTTP_PORT}:80
    privileged: true
    volumes:
     - /sys/fs/cgroup:/sys/fs/cgroup:ro
     - ${BASE_DIR}/proansible/course/common:/common
     - ${BASE_DIR}/proansible/course/control/ansible:/home/ansible
     - ${BASE_DIR}/proansible/course/control/root:/root
    networks:
     - proansible.ai

  ubuntu1:
    hostname: ubuntu1
    container_name: ubuntu1
    image: rheosai/proansible:ubuntu
    ports:
     - ${UBUNTU1_SSH_PORT}:22
     - ${UBUNTU1_HTTP_PORT}:80
    privileged: true
    volumes:
     - /sys/fs/cgroup:/sys/fs/cgroup:ro
     - ${BASE_DIR}/proansible/course/common:/common
     - ${BASE_DIR}/proansible/course/ubuntu1/ansible:/home/ansible
     - ${BASE_DIR}/proansible/course/ubuntu1/root:/root
    networks:
     - proansible.ai

  # ubuntu2:
  #   hostname: ubuntu2
  #   container_name: ubuntu2
  #   image: karrad/proansible:ubuntu
  #   ports:
  #    - ${UBUNTU2_SSH_PORT}:22
  #    - ${UBUNTU2_HTTP_PORT}:80
  #   privileged: true
  #   volumes:
  #    - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #    - /Users/karrad/ans3/common:/common
  #    - /Users/karrad/ans3/ubuntu2/ansible:/home/ansible
  #    - /Users/karrad/ans3/ubuntu2/root:/root
  #   networks:
  #    - proansible.ai

  # alpine1:
  #   hostname: alpine1
  #   container_name: alpine1
  #   image: karrad/proansible:alpine
  #   ports:
  #    - ${ALPINE1_SSH_PORT}:22
  #    - ${ALPINE1_HTTP_PORT}:80
  #   privileged: true
  #   volumes:
  #    - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #    - /Users/karrad/ans3/common:/common
  #    - /Users/karrad/ans3/alpine1/ansible:/home/ansible
  #    - /Users/karrad/ans3/alpine1/root:/root
  #   networks:
  #    - proansible.ai
  
  
  # alpine2:
  #   hostname: alpine2
  #   container_name: alpine2
  #   image: karrad/proansible:alpine
  #   ports:
  #    - ${ALPINE2_SSH_PORT}:22
  #    - ${ALPINE2_HTTP_PORT}:80
  #   privileged: true
  #   volumes:
  #    - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #    - /Users/karrad/ans3/common:/common
  #    - /Users/karrad/ans3/alpine2/ansible:/home/ansible
  #    - /Users/karrad/ans3/alpine2/root:/root
  #   networks:
  #    - proansible.ai

  # centos1:
  #   hostname: centos1
  #   container_name: centos1
  #   image: karrad/proansible:centos
  #   ports:
  #    - ${CENTOS1_SSH_PORT}:22
  #    - ${CENTOS1_HTTP_PORT}:80
  #   privileged: true
  #   volumes:
  #    - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #    - /Users/karrad/ans3/common:/common
  #    - /Users/karrad/ans3/centos1/ansible:/home/ansible
  #    - /Users/karrad/ans3/centos1/root:/root
  #   networks:
  #    - proansible.ai

  # centos2:
  #   hostname: centos2
  #   container_name: centos2
  #   image: karrad/proansible:centos
  #   ports:
  #    - ${CENTOS2_SSH_PORT}:22
  #    - ${CENTOS2_HTTP_PORT}:80
  #   privileged: true
  #   volumes:
  #    - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #    - /Users/karrad/ans3/common:/common
  #    - /Users/karrad/ans3/centos2/ansible:/home/ansible
  #    - /Users/karrad/ans3/centos2/root:/root
  #   networks:
  #    - proansible.ai

  # suse1:
  #   hostname: suse1
  #   container_name: suse1
  #   image: karrad/proansible:opensuse
  #   ports:
  #    - ${SUSE1_SSH_PORT}:22
  #    - ${SUSE1_HTTP_PORT}:80
  #   privileged: true
  #   volumes:
  #    - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #    - /Users/karrad/ans3/common:/common
  #    - /Users/karrad/ans3/suse1/ansible:/home/ansible
  #    - /Users/karrad/ans3/suse1/root:/root
  #   networks:
  #    - proansible.ai

  # suse2:
  #   hostname: suse2
  #   container_name: suse2
  #   image: karrad/proansible:opensuse
  #   ports:
  #    - ${SUSE2_SSH_PORT}:22
  #    - ${SUSE2_HTTP_PORT}:80
  #   privileged: true
  #   volumes:
  #    - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #    - /Users/karrad/ans3/common:/common
  #    - /Users/karrad/ans3/suse2/ansible:/home/ansible
  #    - /Users/karrad/ans3/suse2/root:/root
  #   networks:
  #    - proansible.ai

  # debian1:
  #   hostname: debian1
  #   container_name: debian1
  #   image: karrad/proansible:debian
  #   ports:
  #    - ${DEBIAN1_SSH_PORT}:22
  #    - ${DEBIAN1_HTTP_PORT}:80
  #   privileged: true
  #   volumes:
  #    - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #    - /Users/karrad/ans3/common:/common
  #    - /Users/karrad/ans3/debian1/ansible:/home/ansible
  #    - /Users/karrad/ans3/debian1/root:/root
  #   networks:
  #    - proansible.ai

  
  # debian2:
  #   hostname: debian2
  #   container_name: debian2
  #   image: karrad/proansible:debian
  #   ports:
  #    - ${DEBIAN2_SSH_PORT}:22
  #    - ${DEBIAN2_HTTP_PORT}:80
  #   privileged: true
  #   volumes:
  #    - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #    - /Users/karrad/ans3/common:/common
  #    - /Users/karrad/ans3/debian2/ansible:/home/ansible
  #    - /Users/karrad/ans3/debian2/root:/root
  #   networks:
  #    - proansible.ai

  # rhel1:
  #   hostname: rhel1
  #   container_name: rhel1
  #   image: karrad/proansible:rhel
  #   ports:
  #    - ${RHEL1_SSH_PORT}:22
  #    - ${RHEL1_HTTP_PORT}:80
  #   privileged: true
  #   volumes:
  #    - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #    - /Users/karrad/ans3/common:/common
  #    - /Users/karrad/ans3/rhel1/ansible:/home/ansible
  #    - /Users/karrad/ans3/rhel1/root:/root
  #   networks:
  #    - proansible.ai
  
  # rhel2:
  #   hostname: rhel2
  #   container_name: rhel2
  #   image: karrad/proansible:rhel
  #   ports:
  #    - ${RHEL2_SSH_PORT}:22
  #    - ${RHEL2_HTTP_PORT}:80
  #   privileged: true
  #   volumes:
  #    - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #    - /Users/karrad/ans3/common:/common
  #    - /Users/karrad/ans3/rhel2/ansible:/home/ansible
  #    - /Users/karrad/ans3/rhel2/root:/root
  #   networks:
  #    - proansible.ai
  
  # oracle1:
  #   hostname: oracle1
  #   container_name: oracle1
  #   image: karrad/proansible:oracle
  #   ports:
  #    - ${ORACLE1_SSH_PORT}:22
  #    - ${ORACLE1_HTTP_PORT}:80
  #   privileged: true
  #   volumes:
  #    - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #    - /Users/karrad/ans3/common:/common
  #    - /Users/karrad/ans3/oracle1/ansible:/home/ansible
  #    - /Users/karrad/ans3/oracle1/root:/root
  #   networks:
  #    - proansible.ai
  
  # oracle2:
  #   hostname: oracle2
  #   container_name: oracle2
  #   image: karrad/proansible:oracle
  #   ports:
  #    - ${ORACLE2_SSH_PORT}:22
  #    - ${ORACLE2_HTTP_PORT}:80
  #   privileged: true
  #   volumes:
  #    - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #    - /Users/karrad/ans3/common:/common
  #    - /Users/karrad/ans3/oracle2/ansible:/home/ansible
  #    - /Users/karrad/ans3/oracle2/root:/root
  #   networks:
  #    - proansible.ai
  

    
  # fedora1:
  #   hostname: fedora1
  #   container_name: fedora1
  #   image: karrad/proansible:fedora
  #   ports:
  #    - ${FEDORA1_SSH_PORT}:22
  #    - ${FEDORA1_HTTP_PORT}:80
  #   privileged: true
  #   volumes:
  #    - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #    - /Users/karrad/ans3/common:/common
  #    - /Users/karrad/ans3/fedora1/ansible:/home/ansible
  #    - /Users/karrad/ans3/fedora1/root:/root
  #   networks:
  #    - proansible.ai

  
  # fedora2:
  #   hostname: fedora2
  #   container_name: fedora2
  #   image: karrad/proansible:fedora
  #   ports:
  #    - ${FEDORA2_SSH_PORT}:22
  #    - ${FEDORA2_HTTP_PORT}:80
  #   privileged: true
  #   volumes:
  #    - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #    - /Users/karrad/ans3/common:/common
  #    - /Users/karrad/ans3/fedora2/ansible:/home/ansible
  #    - /Users/karrad/ans3/fedora2/root:/root
  #   networks:
  #    - proansible.ai

  # arch1:
  #   hostname: arch1
  #   container_name: arch1
  #   image: karrad/proansible:arch
  #   ports:
  #    - ${ARCH1_SSH_PORT}:22
  #    - ${ARCH1_HTTP_PORT}:80
  #   privileged: true
  #   volumes:
  #    - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #    - /Users/karrad/ans3/common:/common
  #    - /Users/karrad/ans3/arch1/ansible:/home/ansible
  #    - /Users/karrad/ans3/arch1/root:/root
  #   networks:
  #    - proansible.ai


  # arch2:
  #   hostname: arch2
  #   container_name: arch2
  #   image: karrad/proansible:arch
  #   ports:
  #    - ${ARCH2_SSH_PORT}:22
  #    - ${ARCH2_HTTP_PORT}:80
  #   privileged: true
  #   volumes:
  #    - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #    - /Users/karrad/ans3/common:/common
  #    - /Users/karrad/ans3/arch2/ansible:/home/ansible
  #    - /Users/karrad/ans3/arch2/root:/root
  #   networks:
  #    - proansible.ai
  
  # photon1:
  #   hostname: photon1
  #   container_name: photon1
  #   image: karrad/proansible:photon
  #   ports:
  #    - ${PHOTON1_SSH_PORT}:22
  #    - ${PHOTON1_HTTP_PORT}:80
  #   privileged: true
  #   volumes:
  #    - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #    - /Users/karrad/ans3/common:/common
  #    - /Users/karrad/ans3/photon1/ansible:/home/ansible
  #    - /Users/karrad/ans3/photon1/root:/root
  #   networks:
  #    - proansible.ai

    
  # photon2:
  #   hostname: photon2
  #   container_name: photon2
  #   image: karrad/proansible:photon
  #   ports:
  #    - ${PHOTON2_SSH_PORT}:22
  #    - ${PHOTON2_HTTP_PORT}:80
  #   privileged: true
  #   volumes:
  #    - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #    - /Users/karrad/ans3/common:/common
  #    - /Users/karrad/ans3/photon2/ansible:/home/ansible
  #    - /Users/karrad/ans3/photon2/root:/root
  #   networks:
  #    - proansible.ai

  
  # amazon1:
  #   hostname: amazon1
  #   container_name: amazon1
  #   image: karrad/proansible:amazon
  #   ports:
  #    - ${AMAZON1_SSH_PORT}:22
  #    - ${AMAZON1_HTTP_PORT}:80
  #   privileged: true
  #   volumes:
  #    - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #    - /Users/karrad/ans3/common:/common
  #    - /Users/karrad/ans3/amazon1/ansible:/home/ansible
  #    - /Users/karrad/ans3/amazon1/root:/root
  #   networks:
  #    - proansible.ai

  
  # amazon2:
  #   hostname: amazon2
  #   container_name: amazon2
  #   image: karrad/proansible:amazon
  #   ports:
  #    - ${AMAZON2_SSH_PORT}:22
  #    - ${AMAZON2_HTTP_PORT}:80
  #   privileged: true
  #   volumes:
  #    - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #    - /Users/karrad/ans3/common:/common
  #    - /Users/karrad/ans3/amazon2/ansible:/home/ansible
  #    - /Users/karrad/ans3/amazon2/root:/root
  #   networks:
  #    - proansible.ai